flat_build_targets_pipeline.Rmd:
  path: dev/flat_build_targets_pipeline.Rmd
  state: active
  R: R/build_targets_pipeline.R
  tests: tests/testthat/test-build_targets_pipeline.R
  vignettes: vignettes/pipeline-definition.Rmd
  inflate:
    flat_file: dev/flat_build_targets_pipeline.Rmd
    vignette_name: Pipeline Definition
    open_vignette: false
    check: false
    document: true
    overwrite: ask
    clean: true
    codecov: false
flat_full.Rmd:
  path: dev/flat_full.Rmd
  state: active
  R:
  - R/my_median.R
  - R/my_other_median.R
  tests:
  - tests/testthat/test-my_median.R
  - tests/testthat/test-my_other_median.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_full.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_link_inputs.Rmd:
  path: dev/flat_link_inputs.Rmd
  state: active
  R: R/link_inputs.R
  tests: tests/testthat/test-link_inputs.R
  vignettes: vignettes/linking-input-data.Rmd
  inflate:
    flat_file: dev/flat_link_inputs.Rmd
    vignette_name: Linking Input Data
    open_vignette: false
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
