# WARNING - Generated by {fusen} from dev/flat_link_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("link_inputs works", {
  expect_true(inherits(link_inputs, "function"))
})
