# WARNING - Generated by {fusen} from dev/flat_build_targets_pipeline.Rmd: do not edit by hand # nolint: line_length_linter.

#' Build Targets Pipeline
#'
#' Dynamically build the targets pipeline for the project.
#' 
#' This function sets up the targets pipeline by defining a local `_targets.R` file
#' and using `tar_tangle()` to create the necessary targets from an Rmd file.
#' The Rmd file is, itself, this vignette — Pipeline Definition.
#' 
#' @importFrom glue glue
#' @importFrom here here
#' @return 1
#' @export
#' @examples
#' #build_targets_pipeline()
build_targets_pipeline <- function(
  targets_notebook_name = "_target_notebook.Rmd", 
  targets_file_name = "_targets.R", 
  pkg_name = "MadagascarWeatherStations", 
  vignette_name = "pipeline-definition.Rmd",
  overwrite = FALSE
  ) {
  
  # Define the path to the targets notebook definition and file
  targets_notebook <- here::here(targets_notebook_name)
  targets_file <- here::here(targets_file_name)

  # fetch this installed vignette
  # v <- vignette(vignette_name, package = pkg_name)
  # vignette_path <- fs::path(v$Dir, "doc", v$File)

  vignette_path <- system.file(vignette_name, package = pkg_name)

  # assert that the vignette exists
  if (!fs::file_exists(vignette_path)) {
    cli::cli_alert_danger("Vignette '{vignette_name}' not found in package '{pkg_name}'.")
    stop("Cannot proceed without the vignette file.")
  }

  # copy to local project
  fs::file_copy(vignette_path, targets_notebook, overwrite = overwrite)
  # remove irrelevant quarto directives
  lines <- readr::read_lines(targets_notebook) %>%
    stringr::str_subset("#\\| eval: no", negate = TRUE)
  writeLines(lines, targets_notebook)
  cli::cli_alert_success("Created local targets notebook file at: {targets_notebook}")

  # fetch the installed template for _targets.R
  template_path <- system.file("_targets.R", package = pkg_name)

  # copy to local project
  fs::file_copy(template_path, targets_file, overwrite = overwrite)
  cli::cli_alert_success("Created local targets file at: {targets_file}")

  # replace the tar_tangle() default to use the local notebook name
  if(targets_notebook_name != "_target_notebook.Rmd") {
    
    xfun::gsub_file(
      targets_file,
      pattern = "_target_notebook.Rmd",
      replacement = targets_notebook_name
    )
    cli::cli_alert_success("Updated targets file to use targets notebook: {targets_notebook_name}")
    
  }

  cli::cli_alert_info("To build the base pipeline, run `targets::tar_make()` in your R console. Use `targets::tar_read()` or `targets::tar_load()` to access target outputs.")
  cli::cli_alert_info("You can also edit the targets file to extend the pipeline as needed for your project.")

  return(invisible())
}
